import { Routes } from '@angular/router';
import { MiddleCategoryModule } from './categories/pages/middle-category/middle-category.module';

const middleCategoryRoutes: Routes = [
    {path: 'mobile-phones/c80003', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'all-tv/c80037', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'dvd-hd-players/c80011', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'recivers/c80013', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'tuners/c80015', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'portativnaya-ehlektronika/c130309', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'e-books/c80023', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'mp3/c80016', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'recorders/p202591', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'docing_stations/c236805', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'portativnaya-ehlektronika/c130310', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'universalnye-mobilnye-batarei/c387969', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'zaryadnie-stantsii/c4674585', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'fotoelektricheskie-paneli/c4629920', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'dvd-hd-players/c80011', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'notebooks/c800041', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'accessories/c800892', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'motherboards/c80082', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'processors/c80083', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'soundcards/c80088', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'office-equipment/c802543', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'printers/c80007', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'scanners/c80028', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'tablets/c802554', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'clean_robots/c237815', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'coffee_machines/c80164', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'bigbt/c80080', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'refrigerators/c80125', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'washing_machines/c80124', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'tehnika-dlya-kuhni/c435974', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'cleaning/c435964', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'beauty/c80256', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'playstation-store/c800801', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'playstation-5/k80126', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'gamepads-playstation/k80125', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'velosipedy-i-aksessuary/c83882', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'fishing/c84703', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'reels/c84712', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'skovorody/c4626754', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'kresla/c4657815', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'mebel/c152458', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'videocards/c80087', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'hdd/c80084', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'ssd/c80109', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'office-phones/c80029', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'freezers/c80203', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
    {path: 'men_electric_shavers/c81226', loadChildren: () => import('./categories/pages/middle-category/middle-category.module').then((m) => m.MiddleCategoryModule)},
];

export { middleCategoryRoutes };
